# Generated by Django 2.1.7 on 2019-04-14 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190407_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='profilephotos/default.png', upload_to='profilephotos'),
        ),
    ]
