# Generated by Django 2.1.7 on 2019-04-17 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_auto_20190409_0227'),
        ('accounts', '0005_auto_20190414_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='card',
            field=models.ManyToManyField(related_name='card', to='courses.Course'),
        ),
    ]
