# Generated by Django 2.1.7 on 2019-04-18 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_auto_20190409_0227'),
        ('accounts', '0006_profile_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='card',
        ),
        migrations.AddField(
            model_name='profile',
            name='cart',
            field=models.ManyToManyField(related_name='cart', to='courses.Course'),
        ),
    ]
