# Generated by Django 2.1.7 on 2019-04-06 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(null=True, upload_to='videos/')),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='publish_date',
        ),
        migrations.AddField(
            model_name='category',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='thumbnails/category/'),
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='promotion',
            field=models.FileField(null=True, upload_to='promotions/'),
        ),
        migrations.AddField(
            model_name='course',
            name='purchased',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='skill',
            field=models.CharField(choices=[('Beginner', 'beginner'), ('Intermediate', 'intermediate'), ('Expert', 'expert')], default='beginner', max_length=12),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='thumbnails/course/'),
        ),
        migrations.AddField(
            model_name='course',
            name='content',
            field=models.ManyToManyField(to='courses.Videos'),
        ),
    ]
