# Generated by Django 2.1.7 on 2019-04-05 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='publish_date',
        ),
        migrations.AddField(
            model_name='category',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='tgumbnails/category/'),
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='purchased',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='skill',
            field=models.CharField(choices=[('b', 'beginner'), ('i', 'intermediate'), ('a', 'advanced')], default='b', max_length=12),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='thumbnails/course/'),
        ),
        migrations.AddField(
            model_name='course',
            name='video',
            field=models.FileField(null=True, upload_to='videos/'),
        ),
    ]
