# Generated by Django 2.1.7 on 2019-04-06 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20190406_1902'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='content',
            new_name='video',
        ),
    ]
