# Generated by Django 2.1.7 on 2019-04-02 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_tutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='purchased',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
