# Generated by Django 2.1.7 on 2019-04-05 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20190405_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='skill',
            field=models.CharField(choices=[('Beginner', 'beginner'), ('Intermediate', 'intermediate'), ('Expert', 'expert')], default='b', max_length=12),
        ),
    ]
