# Generated by Django 2.1.7 on 2019-04-06 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20190406_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
