# Generated by Django 2.1.7 on 2019-04-02 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20190402_1516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='tutor',
            new_name='teacher',
        ),
    ]
