# Generated by Django 2.1.7 on 2019-04-06 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20190406_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.FloatField(default=10),
        ),
        migrations.AddField(
            model_name='videos',
            name='altname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
