# Generated by Django 2.1.7 on 2019-04-08 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20190406_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='duration',
            field=models.DurationField(null=True, verbose_name=models.FileField(null=True, upload_to='videos/')),
        ),
    ]
