# Generated by Django 2.1.7 on 2019-04-03 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='publish_date',
        ),
        migrations.AddField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='thumbnails/'),
        ),
    ]
