# Generated by Django 2.1.7 on 2019-04-08 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20190408_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videos',
            name='duration',
        ),
        migrations.AddField(
            model_name='videos',
            name='place',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
