# Generated by Django 2.1.7 on 2019-04-08 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20190408_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='slug',
            field=models.SlugField(max_length=3, null=True, unique=True),
        ),
    ]
