# Generated by Django 2.1.7 on 2019-04-08 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_auto_20190409_0216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videos',
            old_name='slug',
            new_name='videoslug',
        ),
    ]
